### PR TITLE
Added Nullstone as pledge, alphabetized pledges

### PR DESCRIPTION
**Pull request by BSick7**

### CODE REVIEW

**Comment by SebastianStadil** [comment]
Love it! Thanks for your support.

Pledge order is currently non-obvious, but ordered first by committed FTEs, then by community size, then alphabetically. See #48 

Could you add Nullstone alphabetically starting after Gruntwork?

**Comment by SebastianStadil** [comment]
Nevermind, we're just going to append now.

**Review by SebastianStadil — CHANGES_REQUESTED** [review]
Can you leave the order as is, and just append your org to the list?

**Comment by BSick7** [comment]
I can do that; however, basing off FTE/community size is going to be a nightmare to track.
Not to mention, that goes against the "impartial" section of the manifesto.

**Comment by BSick7** [comment]
@SebastianStadil I reverted the order.

**Comment by SebastianStadil** [comment]
You're right! And sorry, we went back and forth a few times on how to order.

**Comment by BSick7** [comment]
@brikis98 Made adjustments.

**Comment by josh-padnick** [comment]
Added in #91

**Pull request closed without merging**
