### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by zero-pytagoras**
adding myself to manifesto

### CODE REVIEW

**Review by flavius-dinu — CHANGES_REQUESTED** [review]
You are missing a `</tr>`.

**Review by marcinwyszynski — DISMISSED** [review]
The profile link seems to be broken.

**Review by marcinwyszynski — CHANGES_REQUESTED** [review]
The profile link seems to be broken.

**Review by flavius-dinu — CHANGES_REQUESTED** [review]
We still need the opening `<tr>` for the next person.

**Comment by flavius-dinu** [comment]
Added in https://github.com/opentffoundation/manifesto/pull/266

**Pull request closed without merging**
