### PR TITLE
add coherence to supporters list

### PR DESCRIPTION
**Pull request by zach-withcoherence**
thanks!

### CODE REVIEW

**Review by SebastianStadil — CHANGES_REQUESTED** [review]
We decided to append pledges to keep things impartial, can you add your org at the bottom?

**Comment by zach-withcoherence** [comment]
Sure thing, thanks!

**Comment by zach-withcoherence** [comment]
@brikis98 - sure thing, thanks!

**Review by josh-padnick — APPROVED** [review]

**Comment by josh-padnick** [comment]
@SebastianStadil Could you review and merge?

**Comment by josh-padnick** [comment]
Added in #91

**Pull request closed without merging**
