### PR TITLE
Add Adam Walton to signees of document

### PR DESCRIPTION
**Pull request by arwalton**

### CODE REVIEW

**Comment by flavius-dinu** [comment]
@arwalton Can you solve the conflicts? Thanks!

**Comment by arwalton** [comment]
Should be resolved now

**Comment by flavius-dinu** [comment]
There is a `<tr>` missing after your `</tr>`

**Review by flavius-dinu — APPROVED** [review]

**Comment by arwalton** [comment]
Thanks!

**Pull request merged**
